[project]
name = "ninjserv-daily-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.5.2",
    "openai>=1.90.0",
    "python-dotenv>=1.1.0",
]
